apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'example-variables'
spec:
  selector:
    matchLabels:
      app: variables
  replicas: 2
  template:
    metadata:
      labels:
        app: variables
    spec:
      containers:
        - name: variables
          image: gcr.io/google-samples/node-hello:1.0
          env:
          - name: NAME
            value: "OPENSHIFT COURSE"
          - name: OWNER
            value: "Apasoft Training"
          
